apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetlinux
  labels:
    app: dotnetlinux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetlinux
  template:
    metadata:
      labels:
        app: dotnetlinux
    spec:
      containers:
        - image: "hackersmooth88/asp"
          imagePullPolicy: Always
          name: dotnetlinux
          ports:
            - containerPort: 80
